<?php
$canonical = $_SERVER['SCRIPT_NAME'] === '/index.php' ? '/' : str_replace('.php', '', $_SERVER['SCRIPT_NAME']);
?>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="canonical" href="<?php echo $canonical; ?>" />
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta http-equiv="Cache-control" content="no-cache"/>
  <meta name="description" content="Prutrace De Weere">
  <meta name="author" content="Sjoerd en Freek">

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>

  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

  <!-- Custom styles for this template -->
  <link rel="stylesheet" type="text/css" href="/assets/style/style.css" media="screen">

  <!-- Flavicon ico -->
  <link rel="apple-touch-icon" sizes="180x180" href="/assets/img/flavicon/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/assets/img/flavicon/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/assets/img/flavicon/favicon-16x16.png">
  <link rel="manifest" href="/assets/img/flavicon/site.webmanifest">

  <title>Prutrace De Weere</title>
</head>