<?php
$current_url = $_SERVER['SCRIPT_NAME'];
?>
<nav class="navbar navbar-expand-md navbar-dark">
  <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link<?php print ($current_url === '/index.php' ? ' active' : ''); ?>" href="/index">Prut home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link<?php print ($current_url === '/inschrijven.php' ? ' active' : ''); ?>" href="/inschrijven">Inschrijven / Regelement</a>
      </li>
      <li class="nav-item">
        <a class="nav-link<?php print ($current_url === '/parcours.php' ? ' active' : ''); ?>" href="/parcours">Parcours</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="" id="dropdown" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">Foto's</a>
        <div class="dropdown-menu" aria-labelledby="dropdown">
          <a class="dropdown-item" href="https://onswestfriesland.nl/fotos-prutrace-de-weere-2018-start/"
            target="_blank">2018 - 
            Foto's OnsWestFriesland</a>
          <a class="dropdown-item"
            href="https://www.facebook.com/pg/prutracedeweere/photos/?tab=album&album_id=1401948853254287"
            target="_blank">2017 - 
            Foto's José Kappelhof</a>
          <a class="dropdown-item" href="http://www.opmeeractueel.nl/prutloop_16/" target="_blank">2016 - 
            Foto's Ted Friethoff</a>
          <a class="dropdown-item" href="http://www.opmeeractueel.nl/prutloop_15/" target="_blank">2015 - 
            Foto's Ted Friethoff</a>
          <a class="dropdown-item" href="http://www.opmeeractueel.nl/prutloop_14/" target="_blank">2014 - 
            Foto's Ted Friethoff</a>
          <a class="dropdown-item" href="http://www.opmeeractueel.nl/prutloop_13/" target="_blank">2013 - 
            Foto's Ted Friethoff</a>
          <a class="dropdown-item" href="http://www.opmeeractueel.nl/prutloop_12/" target="_blank">2012 - 
            Foto's Ted Friethoff</a>
          <a class="dropdown-item" href="http://www.opmeeractueel.nl/prutloop_11/" target="_blank">2011 - 
            Foto's Ted Friethoff</a>
          <a class="dropdown-item" href="http://www.opmeeractueel.nl/prutloop_10/" target="_blank">2010 - 
            Foto's Ted Friethoff</a>
          <a class="dropdown-item" href="http://www.opmeeractueel.nl/prutloop_09/" target="_blank">2009 - 
            Foto's Ted Friethoff</a>
          <a class="dropdown-item" href="http://www.opmeeractueel.nl/10e_prutrace/" target="_blank">2008 - 
            Foto's Ted Friethoff</a>
        </div>
      </li>
    </ul>
  </div>
  <div class="mr-auto order-0">
    <a class="navbar-brand mx-auto<?php print ($current_url === '/index.php' ? ' active' : ''); ?>" href="/index">Prutrace De Weere</a>
  </div>
  <div class="ml-auto">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
  <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link<?php print ($current_url === '/videos.php' ? ' active' : ''); ?>" href="/videos">Video's</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="" id="dropdown" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">Uitslagen</a>
        <div class="dropdown-menu" aria-labelledby="dropdown">
          <a class="dropdown-item" href="https://results.chronotrack.com/event/results/event/event-41595"
            target="_blank">Uitslag
            2018</a>
          <a class="dropdown-item" href="https://results.chronotrack.com/event/results/event/event-31682"
            target="_blank">Uitslag
            2017</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link<?php print ($current_url === '/sponsors.php' ? ' active' : ''); ?>" href="/sponsors">Sponsors</a>
      </li>
      <li class="nav-item">
        <a class="nav-link<?php print ($current_url === '/contact.php' ? ' active' : ''); ?>" href="/contact">Contact</a>
      </li>
    </ul>
  </div>
</nav>

<script src="/assets/scripts/dropdown.js" type="text/javascript"></script>
